export default {
  login: 'clinzy25',
  id: 74991878,
  node_id: 'MDQ6VXNlcjc0OTkxODc4',
  avatar_url: 'https://avatars.githubusercontent.com/u/74991878?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/clinzy25',
  html_url: 'https://github.com/clinzy25',
  followers_url: 'https://api.github.com/users/clinzy25/followers',
  following_url: 'https://api.github.com/users/clinzy25/following{/other_user}',
  gists_url: 'https://api.github.com/users/clinzy25/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/clinzy25/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/clinzy25/subscriptions',
  organizations_url: 'https://api.github.com/users/clinzy25/orgs',
  repos_url: 'https://api.github.com/users/clinzy25/repos',
  events_url: 'https://api.github.com/users/clinzy25/events{/privacy}',
  received_events_url: 'https://api.github.com/users/clinzy25/received_events',
  type: 'User',
  site_admin: false,
  name: 'Conner Linzy',
  company: 'N/A',
  blog: 'linzy.tech',
  location: 'Charlotte, NC',
  email: null,
  hireable: true,
  bio: 'Web Developer',
  twitter_username: null,
  public_repos: 14,
  public_gists: 0,
  followers: 1,
  following: 1,
  created_at: '2020-11-24T21:47:23Z',
  updated_at: '2021-04-12T12:18:45Z',
};
